redis:
  host: baasnode-server-redis
  port: 6379
  pass:
  maxConn: 100

baasnode:
  protocol: tcp
  port: 6750
  httpport: 6751

wallet:
  host: wallet-server-test
  port: 6010

risk:
  host: risk-server-test.walletrc
  port: 6060
